"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FormField } from "@/components/admin/form-field";
import { PageHeader } from "@/components/admin/page-header";
import { createBrandSchema, type CreateBrandInput } from "@/schemas/brand";
import { createBrandAction } from "@/actions/brands";
import { useTranslation } from "@/hooks/use-translation";
import { cn } from "@/lib/utils";
import Link from "next/link";

function toSlug(s: string) {
  return s.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

export default function NewBrandPage() {
  const router = useRouter();
  const { t, locale } = useTranslation();
  const isAr = locale === "ar";
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<CreateBrandInput>({
    resolver: zodResolver(createBrandSchema),
    defaultValues: { isActive: true, isFeatured: false, sortOrder: 0 },
  });

  const textareaClass =
    "flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

  const onSubmit = async (data: CreateBrandInput) => {
    setIsSubmitting(true);
    try {
      const result = await createBrandAction(data);
      if (!result.success) {
        toast.error(result.error ?? (isAr ? "فشل الإنشاء" : "Failed to create"));
        return;
      }
      toast.success(t("brandCreated"));
      router.push("/admin/brands");
    } catch {
      toast.error(isAr ? "حدث خطأ ما" : "Something went wrong");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6" dir={isAr ? "rtl" : "ltr"}>
      <PageHeader
        title={t("addBrand")}
        description={isAr ? "أنشئ ماركة منتجات جديدة" : "Create a new product brand"}
      >
        <Button >
          <Link href="/admin/brands">
            <ArrowLeft className={cn("h-4 w-4", isAr && "rotate-180")} />
            {t("back")}
          </Link>
        </Button>
      </PageHeader>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">

          {/* ── Main column ─────────────────────────────────────────────────── */}
          <div className="space-y-6 lg:col-span-2">

            <Card>
              <CardHeader>
                <CardTitle className="text-base">
                  {isAr ? "معلومات الماركة" : "Brand Information"}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">

                {/* Name EN + AR */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <FormField label={t("brandName")} required error={errors.name?.message}>
                    <Input
                      {...register("name")}
                      placeholder={isAr ? "مثال: Apple" : "e.g. Apple"}
                      onChange={(e) => {
                        setValue("name", e.target.value);
                        setValue("slug", toSlug(e.target.value));
                      }}
                    />
                  </FormField>
                  <FormField label={t("brandNameAr")} error={errors.nameAr?.message}>
                    <Input
                      {...register("nameAr")}
                      placeholder="مثال: آبل"
                      dir="rtl"
                    />
                  </FormField>
                </div>

                {/* Slug */}
                <FormField label={t("slug")} required error={errors.slug?.message} hint={t("slugAutoGenerated")}>
                  <Input {...register("slug")} placeholder="apple" className="font-mono text-sm" />
                </FormField>

                {/* Description EN + AR */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <FormField label={t("brandDescription")} error={errors.description?.message}>
                    <textarea
                      {...register("description")}
                      rows={3}
                      placeholder={isAr ? "وصف الماركة بالإنجليزية..." : "Brand description..."}
                      className={textareaClass}
                    />
                  </FormField>
                  <FormField label={t("brandDescriptionAr")} error={errors.description?.message}>
                    <textarea
                      rows={3}
                      dir="rtl"
                      placeholder="وصف الماركة بالعربية..."
                      className={textareaClass}
                    />
                  </FormField>
                </div>

                {/* Logo + Website */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <FormField
                    label={t("logoUrl")}
                    error={errors.logo?.message}
                    hint={t("logoUrlHint")}
                  >
                    <Input {...register("logo")} placeholder="https://..." />
                  </FormField>
                  <FormField label={t("website")} error={errors.website?.message}>
                    <Input {...register("website")} placeholder="https://apple.com" type="url" />
                  </FormField>
                </div>

                {/* Logo Preview */}
                <LogoPreview register={register} />
              </CardContent>
            </Card>

            {/* SEO */}
            <Card>
              <CardHeader><CardTitle className="text-base">{t("seo")} ({t("optional")})</CardTitle></CardHeader>
              <CardContent className="space-y-4">
                <FormField label={t("metaTitle")} hint={isAr ? "حد أقصى 60 حرف" : "Max 60 chars"}>
                  <Input {...register("metaTitle")} maxLength={60} />
                </FormField>
                <FormField label={t("metaDescription")} hint={isAr ? "حد أقصى 160 حرف" : "Max 160 chars"}>
                  <textarea {...register("metaDescription")} rows={2} maxLength={160} className={textareaClass} />
                </FormField>
              </CardContent>
            </Card>
          </div>

          {/* ── Right column ───────────────────────────────────────────────── */}
          <div className="space-y-6">
            <Card>
              <CardHeader><CardTitle className="text-base">{t("settings")}</CardTitle></CardHeader>
              <CardContent className="space-y-3">
                <label className="flex cursor-pointer items-center justify-between rounded-lg border p-3 hover:bg-muted/50">
                  <div>
                    <p className="text-sm font-medium">{t("active")}</p>
                    <p className="text-xs text-muted-foreground">{t("visibleInStore")}</p>
                  </div>
                  <input type="checkbox" {...register("isActive")} className="h-4 w-4 accent-primary" />
                </label>
                <label className="flex cursor-pointer items-center justify-between rounded-lg border p-3 hover:bg-muted/50">
                  <div>
                    <p className="text-sm font-medium">{t("featured")}</p>
                    <p className="text-xs text-muted-foreground">{t("showOnHomepage")}</p>
                  </div>
                  <input type="checkbox" {...register("isFeatured")} className="h-4 w-4 accent-primary" />
                </label>
                <FormField label={t("sortOrder")} hint={isAr ? "الأصغر يظهر أولاً" : "Lower = appears first"}>
                  <Input {...register("sortOrder", { valueAsNumber: true })} type="number" min="0" />
                </FormField>
              </CardContent>
            </Card>

            <Button type="submit" className="w-full" size="lg" loading={isSubmitting}>
              {t("createBrand")}
            </Button>
          </div>
        </div>
      </form>
    </div>
  );
}

// ── Logo preview sub-component ────────────────────────────────────────────────
function LogoPreview({ register }: { register: ReturnType<typeof useForm<CreateBrandInput>>["register"] }) {
  // We can't use watch here easily without passing it down, so we use a simple state
  return null; // Placeholder — logo preview can be added with useWatch
}
