"use client";

import { useState } from "react";
import { useRouter, useParams } from "next/navigation";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import { Plus, Trash2, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FormField } from "@/components/admin/form-field";
import { PageHeader } from "@/components/admin/page-header";
import { createCategorySchema, type CreateCategoryInput } from "@/schemas/category";
import { createStoreCategoryAction } from "@/actions/categories";
import { useTranslation } from "@/hooks/use-translation";
import { cn } from "@/lib/utils";
import Link from "next/link";

function toSlug(s: string) {
  return s.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

export default function NewCategoryPage() {
  const router = useRouter();
  const params = useParams<{ storeSlug: string }>();
  const storeSlug = params.storeSlug || "";
  const { t, locale } = useTranslation();
  const isAr = locale === "ar";
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    control,
    formState: { errors },
  } = useForm<CreateCategoryInput>({
    resolver: zodResolver(createCategorySchema),
    defaultValues: {
      isActive: true,
      isFeatured: false,
      sortOrder: 0,
      subcategories: [],
    },
  });

  const { fields, append, remove } = useFieldArray({ control, name: "subcategories" });

  const textareaClass =
    "flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

  const onSubmit = async (data: CreateCategoryInput) => {
    setIsSubmitting(true);
    try {
      const result = await createStoreCategoryAction(storeSlug, data);
      if (!result.success) {
        toast.error(result.error ?? (isAr ? "فشل الإنشاء" : "Failed to create"));
        return;
      }
      toast.success(t("categoryCreated"));
      router.push(`/dashboard/stores/${storeSlug}/categories`);
    } catch {
      toast.error(isAr ? "حدث خطأ ما" : "Something went wrong");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6" dir={isAr ? "rtl" : "ltr"}>
      <PageHeader
        title={t("addCategory")}
        description={isAr ? "أنشئ فئة منتجات جديدة" : "Create a new product category"}
      >
        <Button >
          <Link href={`/dashboard/stores/${storeSlug}/categories`}>
            <ArrowLeft className={cn("h-4 w-4", isAr && "rotate-180")} />
            {t("back")}
          </Link>
        </Button>
      </PageHeader>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">

          {/* ── Main column ─────────────────────────────────────────────────── */}
          <div className="space-y-6 lg:col-span-2">

            {/* Basic Info */}
            <Card>
              <CardHeader><CardTitle className="text-base">{t("basicInfo")}</CardTitle></CardHeader>
              <CardContent className="space-y-4">

                {/* Name EN + AR */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <FormField label={t("categoryName")} required error={errors.name?.message}>
                    <Input
                      {...register("name")}
                      placeholder={isAr ? "مثال: Electronics" : "e.g. Electronics"}
                      onChange={(e) => {
                        setValue("name", e.target.value);
                        setValue("slug", toSlug(e.target.value));
                      }}
                    />
                  </FormField>
                  <FormField label={t("categoryNameAr")} error={errors.nameAr?.message}>
                    <Input
                      {...register("nameAr")}
                      placeholder="مثال: الإلكترونيات"
                      dir="rtl"
                    />
                  </FormField>
                </div>

                {/* Slug */}
                <FormField label={t("slug")} required error={errors.slug?.message} hint={t("slugAutoGenerated")}>
                  <Input {...register("slug")} placeholder="electronics" className="font-mono text-sm" />
                </FormField>

                {/* Icon */}
                <FormField label={t("icon")} hint={t("iconHint")} error={errors.icon?.message}>
                  <Input {...register("icon")} placeholder="💻" className="w-24 text-xl" />
                </FormField>

                {/* Description EN + AR */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <FormField label={t("categoryDescription")} error={errors.description?.message}>
                    <textarea
                      {...register("description")}
                      rows={3}
                      placeholder={isAr ? "وصف الفئة بالإنجليزية..." : "Category description..."}
                      className={textareaClass}
                    />
                  </FormField>
                  <FormField label={t("categoryDescriptionAr")} error={errors.descriptionAr?.message}>
                    <textarea
                      {...register("descriptionAr")}
                      rows={3}
                      dir="rtl"
                      placeholder="وصف الفئة بالعربية..."
                      className={textareaClass}
                    />
                  </FormField>
                </div>
              </CardContent>
            </Card>

            {/* Subcategories */}
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">{t("subcategories")}</CardTitle>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => append({ name: "", slug: "", isActive: true, sortOrder: fields.length })}
                  >
                    <Plus className="h-4 w-4" /> {t("addSubcategory")}
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                {fields.length === 0 && (
                  <p className="text-sm text-muted-foreground text-center py-4">
                    {t("noSubcategories")}
                  </p>
                )}
                {fields.map((field, idx) => (
                  <div key={field.id} className="rounded-lg border p-3 space-y-2">
                    <div className="grid grid-cols-2 gap-2">
                      {/* Name EN */}
                      <Input
                        {...register(`subcategories.${idx}.name`)}
                        placeholder={t("subcategoryName")}
                        onChange={(e) => {
                          setValue(`subcategories.${idx}.name`, e.target.value);
                          setValue(`subcategories.${idx}.slug`, toSlug(e.target.value));
                        }}
                      />
                      {/* Name AR */}
                      <Input
                        {...register(`subcategories.${idx}.nameAr` as `subcategories.${number}.name`)}
                        placeholder={t("subcategoryNameAr")}
                        dir="rtl"
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      {/* Slug */}
                      <Input
                        {...register(`subcategories.${idx}.slug`)}
                        placeholder={t("slug")}
                        className="flex-1 font-mono text-sm"
                      />
                      {/* Active */}
                      <label className="flex items-center gap-1.5 text-xs text-muted-foreground whitespace-nowrap">
                        <input
                          type="checkbox"
                          {...register(`subcategories.${idx}.isActive`)}
                          defaultChecked
                          className="h-3.5 w-3.5 accent-primary"
                        />
                        {t("active")}
                      </label>
                      {/* Remove */}
                      <button
                        type="button"
                        onClick={() => remove(idx)}
                        className="text-muted-foreground hover:text-destructive transition-colors"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* SEO */}
            <Card>
              <CardHeader><CardTitle className="text-base">{t("seo")} ({t("optional")})</CardTitle></CardHeader>
              <CardContent className="space-y-4">
                <FormField label={t("metaTitle")} hint={isAr ? "حد أقصى 60 حرف" : "Max 60 chars"}>
                  <Input {...register("metaTitle")} maxLength={60} />
                </FormField>
                <FormField label={t("metaDescription")} hint={isAr ? "حد أقصى 160 حرف" : "Max 160 chars"}>
                  <textarea {...register("metaDescription")} rows={2} maxLength={160} className={textareaClass} />
                </FormField>
              </CardContent>
            </Card>
          </div>

          {/* ── Right column ───────────────────────────────────────────────── */}
          <div className="space-y-6">
            <Card>
              <CardHeader><CardTitle className="text-base">{t("settings")}</CardTitle></CardHeader>
              <CardContent className="space-y-3">
                <label className="flex cursor-pointer items-center justify-between rounded-lg border p-3 hover:bg-muted/50">
                  <div>
                    <p className="text-sm font-medium">{t("active")}</p>
                    <p className="text-xs text-muted-foreground">{t("visibleInStore")}</p>
                  </div>
                  <input type="checkbox" {...register("isActive")} className="h-4 w-4 accent-primary" />
                </label>
                <label className="flex cursor-pointer items-center justify-between rounded-lg border p-3 hover:bg-muted/50">
                  <div>
                    <p className="text-sm font-medium">{t("featured")}</p>
                    <p className="text-xs text-muted-foreground">{t("showOnHomepage")}</p>
                  </div>
                  <input type="checkbox" {...register("isFeatured")} className="h-4 w-4 accent-primary" />
                </label>
                <FormField label={t("sortOrder")} hint={isAr ? "الأصغر يظهر أولاً" : "Lower = appears first"}>
                  <Input {...register("sortOrder", { valueAsNumber: true })} type="number" min="0" />
                </FormField>
              </CardContent>
            </Card>

            <Button type="submit" className="w-full" size="lg" loading={isSubmitting}>
              {t("createCategory")}
            </Button>
          </div>
        </div>
      </form>
    </div>
  );
}
